### ISSUE TITLE
Madgraph5 Vector Boson Fusion 

### ISSUE THREAD

**Issue by umar0341** [mg5amcnlo/mg5amcnlo#9] opened 2022-06-24 09:14 UTC
Hello i"m using Madgraph5 package for my work on Muon Collider but when I generate any process Vector Boson Fusion Diagrams are missing due to which my cross section is very small. How can I get all Diagrams to rise up my cross section?
i tried following methods to get them but couldn't. 

 **generate mu+ mu- > h3 h3 QED=2 , h3 > b b~, h3 > b b~ 
generate mu+ mu- > h3 h3, h3 > b b~, h3 > b b~  QED = 2
generate mu+ mu- > h3 h3, h3 > b b~, h3 > b b~   QED = 4
generate mu+ mu- > h3 h3, h3 > b b~, h3 > b b~  QCD = 0
generate mu+ mu- > h3 h3, h3 > b b~, h3 > b b~  QCD = 2
generate mu+ mu- > h3 h3, h3 > b b~, h3 > b b~  QCD = 4
generate mu+ mu- > h3 h3, h3 > b b~, h3 > b b~   QCD = 0 QED = 4**

kindly help me to get Vector Boson Fusion Diagrams to rise up my Cross Section. My  aim is to produce Heavy higgs pair production analysis using Muon Collider in Madgragh5...

**Comment by oliviermattelaer** [comment] 2022-06-27 19:26
Duplicate of https://answers.launchpad.net/mg5amcnlo/+question/702278

**Closed by oliviermattelaer** 2022-06-27 19:26 UTC
